import { Recipe } from '../recipe';
import { RECIPE_TYPES } from './mock-recipe-types';

export const RECIPES: Recipe[] = [
  new Recipe('1', 'Involtini vegetariani', RECIPE_TYPES[0],
    'Involtini Fritti ripieni di verza, carote e cipolle',
    2.0, 2,
    [2, 3, 15, 0]),
  new Recipe('2', 'Involtini di gamberi', RECIPE_TYPES[0],
    'Involtini Fritti ripieni di gambero, verza, carote e cipolle',
    3.5, 2,
    [2, 3, 11, 15, 1]),
  new Recipe('3', 'Involtini Thai di carne', RECIPE_TYPES[0],
    'Involtini Fritti ripieni di carne e verdure miste',
    3.0, 2,
    [2, 3, 10, 15]),
  new Recipe('4', 'Nuvolette di gamberi', RECIPE_TYPES[0],
    'Nuvolette di gambero fritte',
    2.5, null,
    [3, 11, 1], [66]),
  new Recipe('5', 'Pane fritto', RECIPE_TYPES[0],
    'Focaccine cinesi fritte',
    2.0, 2,
    [3, 6, 9, 15, 1]),
  new Recipe('6', 'Pane al vapore', RECIPE_TYPES[0],
    'Focaccine cinesi al vapore',
    2.0, 2,
    [3, 6, 9, 15, 1]),
  new Recipe('7', 'Gyoza yaki', RECIPE_TYPES[0],
    'Ravioli di suino e verdure alla griglia',
    4.5, 4,
    [2, 3, 4, 10]),
  new Recipe('8', 'Ravioli di gamberi', RECIPE_TYPES[0],
    'Ravioli di farina di riso con gambero',
    4.5, 4,
    [2, 4, 11, 10, 15]),
  new Recipe('9', 'Ravioli xiaomai', RECIPE_TYPES[0],
    'Ravioli di gambero, suino e verdure',
    4.5, 4,
    [2, 3, 11, 10, 15]),
  new Recipe('10', 'Ravioli vegetariani', RECIPE_TYPES[0],
    'Ravioli di verdure miste',
    4.0, 4,
    [2, 3, 4, 0]),
  new Recipe('11', 'Ravioli al vapore', RECIPE_TYPES[0],
    'Ravioli di suino e verdure al vapore',
    4.0, 4,
    [2, 3, 4, 10]),
  new Recipe('12', 'Edamame', RECIPE_TYPES[0],
    'Fagioli di soia al vapore',
    3.5, null,
    [4, 15, 0]),
  new Recipe('13', 'Wakame', RECIPE_TYPES[0],
    'Alghe Giapponesi e sesamo',
    3.5, null,
    [2, 15, 0], [72]),
  new Recipe('14', 'Alghe fritte', RECIPE_TYPES[0],
    'Alghe cinesi fritte',
    3.5, null,
    [2, 0]),
  new Recipe('15', 'Takoyaki', RECIPE_TYPES[0],
    'Polpette di polpo fritte',
    4.5, 4,
    [2, 3, 13, 4, 6, 1], [39, 71]),
  new Recipe('16', 'Toast di gamberi', RECIPE_TYPES[0],
    'Pancarrè ripieno di gamberi e sesamo fritto',
    3.5, 4,
    [3, 11, 6, 1]),
  new Recipe('17', 'Sake tataki', RECIPE_TYPES[0],
    'Salmone scottato con crosta di sesamo marinato',
    4.5, 4,
    [13, 4, 15, 1]),
  new Recipe('18', 'Maguro tataki', RECIPE_TYPES[0],
    'Tonno scottato e marinato con arachidi',
    5.0, 4,
    [13, 4, 7, 15, 1]),
  new Recipe('19', 'Ebi su', RECIPE_TYPES[0],
    'Alghe Giapponesi marinate con pollo',
    4.0, null,
    [2, 13, 4, 11, 15, 1]),
  new Recipe('20', 'Tako su', RECIPE_TYPES[0],
    'Alghe Giapponesi marinate con polpo cotto',
    4.0, null,
    [2, 13, 4, 15, 1]),
  new Recipe('21', 'Kaisen salad', RECIPE_TYPES[1],
    'Insalata verde con sashimi',
    6.0, null,
    [2, 13, 11, 14, 15, 1]),
  new Recipe('22', 'Fruit salad', RECIPE_TYPES[1],
    'Insalata verde con frutta di stagione',
    5.0, null,
    [2, 0]),
  new Recipe('23', 'Mango salad', RECIPE_TYPES[1],
    'Insalata verde con mango e arachidi',
    5.0, null,
    [2, 7, 0], [5]),
  new Recipe('24', 'Vegan salad', RECIPE_TYPES[1],
    'Insalata vegana',
    4.0, null,
    [2, 0]),
  new Recipe('25', 'Zuppa di miso', RECIPE_TYPES[2],
    'Zuppa di soia fermentata con toufu e alghe',
    3.5, null,
    [2, 4, 0]),
  new Recipe('26', 'Zuppa agropiccante', RECIPE_TYPES[2],
    'Zuppa con uova, toufu, pollo, bambù e funghi cinesi',
    3.5, null,
    [6, 2, 5, 1]),
  new Recipe('27', 'Zuppa granchio asparagi', RECIPE_TYPES[2],
    'Zuppa con uova, granchio e asparagi',
    3.5, null,
    [6, 2, 11, 15, 1]),
  new Recipe('28', 'Zuppa Tom Yam', RECIPE_TYPES[2],
    'Zuppa di cocco con frutti di mare',
    5.0, null,
    [11, 5, 15, 1]),
  new Recipe('29', 'Zuppa mais e pollo', RECIPE_TYPES[2],
    'Zuppa mais e pollo',
    3.5, null,
    [2, 6, 1]),
  new Recipe('30', 'Ramen di manzo', RECIPE_TYPES[2],
    'Spaghetti di frumento con brodo di manzo, verdure, alghe, mais e uova',
    7.5, null,
    [2, 6, 4, 3], [83, 40]),
  new Recipe('31', 'Kaisen udon', RECIPE_TYPES[2],
    'Spaghetti di grano in brodo con frutti di mare e alghe',
    8.0, null,
    [13, 12, 3, 4, 11, 15, 1]),
  new Recipe('32', 'Riso cantonese', RECIPE_TYPES[3],
    'Riso saltato con uova, piselli e prosciutto',
    5.0, null,
    [2, 6, 10], [83, 56, 60]),
  new Recipe('33', 'Riso gamberi', RECIPE_TYPES[3],
    'Riso saltato con uova, verdure e gamberi',
    5.5, null,
    [2, 6, 11, 1], [83]),
  new Recipe('34', 'Riso terra-mare', RECIPE_TYPES[3],
    'Riso saltato con uova, verdure, pollo, gamberi e manzo',
    6.0, null,
    [2, 6, 11, 4], [83]),
  new Recipe('35', 'Riso vegetariano', RECIPE_TYPES[3],
    'Riso saltato con uova e verdure',
    4.5, null,
    [2, 6, 1], [83]),
  new Recipe('35VEG', 'Riso vegan', RECIPE_TYPES[3],
    'Riso saltato con verdure',
    4.0, null,
    [2, 0], [], [], [],
    '35'),
  new Recipe('36', 'Riso pollo con salsa Teriyaki', RECIPE_TYPES[3],
    `"Riso vegetariano" (34) con pollo e salsa Teriyaki`,
    6.0, null,
    [2, 6, 4], [71]),
  new Recipe('37', 'Riso al curry con manzo', RECIPE_TYPES[3],
    'Riso bianco ricoperto con manzo al curry e verdure',
    6.0, null,
    [2]),
  new Recipe('38', 'Riso al curry con gamberi', RECIPE_TYPES[3],
    'Riso saltato con uova e verdure, con gamberi e curry',
    6.0, null,
    [2, 6, 11, 1]),
  new Recipe('39', 'Riso venere', RECIPE_TYPES[3],
    'Riso venere saltato con uova e verdure, con gamberi e anacardi',
    7.0, null,
    [2, 6, 11, 7, 1], [3]),
  new Recipe('39VEG', 'Riso venere vegan', RECIPE_TYPES[3],
    'Riso venere saltato, con verdure e anacardi',
    6.5, null,
    [2, 7, 0], [3], [], [],
    '39'),
  new Recipe('40', 'Sake don', RECIPE_TYPES[3],
    'Letto di riso ricoperto con salmone scottato',
    9.0, null,
    [3, 12, 4, 1], [71]),
  new Recipe('41', 'Gohan', RECIPE_TYPES[3],
    'Riso in bianco al vapore',
    2.5, null,
    [0]),
  new Recipe('42', 'Yaki udon ai frutti di mare', RECIPE_TYPES[4],
    'Spaghetti di grano saltati con uova, verdure e frutti di mare',
    7.5, null,
    [2, 3, 11, 6, 12, 13, 15, 1], [83]),
  new Recipe('43', 'Yaki udon con pollo', RECIPE_TYPES[4],
    'Spaghetti di grano saltati con uova, verdure e pollo',
    7.0, null,
    [2, 3, 6], [83]),
  new Recipe('44', 'Yaki udon vegetariano', RECIPE_TYPES[4],
    'Spaghetti di grano saltati con uova e verdure',
    6.0, null,
    [2, 3, 4, 6, 1], [83]),
  new Recipe('44VEG', 'Yaki udon vegan', RECIPE_TYPES[4],
    'Spaghetti di grano saltati con verdure',
    5.5, null,
    [2, 3, 4, 0], [], [], [],
    '44'),
  new Recipe('45', 'Yaki soba ai frutti di mare', RECIPE_TYPES[4],
    'Spaghetti di grano saraceno saltati con uova, verdure e frutti di mare',
    7.0, null,
    [2, 3, 11, 6, 12, 13, 1], [83]),
  new Recipe('46', 'Yaki soba con pollo', RECIPE_TYPES[4],
    'Spaghetti di grano saraceno saltati con uova, verdure e pollo',
    6.0, null,
    [2, 3, 6], [83]),
  new Recipe('47', 'Yaki soba vegetariano', RECIPE_TYPES[4],
    'Spaghetti di grano saraceno saltati con uova e verdure',
    5.5, null,
    [2, 3, 6, 1], [83]),
  new Recipe('47VEG', 'Yaki soba vegan', RECIPE_TYPES[4],
    'Spaghetti di grano saraceno saltati con verdure',
    5.0, null,
    [2, 3, 0], [], [], [],
    '47'),
  new Recipe('48', 'Pad Thai ai frutti di mare', RECIPE_TYPES[4],
    'Spaghetti di riso saltati con uova, verdure, frutti di mare e arachidi',
    7.0, null,
    [2, 11, 6, 7, 12, 13, 5, 15, 1], [83, 5]),
  new Recipe('49', 'Pad Thai con pollo', RECIPE_TYPES[4],
    'Spaghetti di riso saltati con uova, verdure, pollo e arachidi',
    6.5, null,
    [2, 6, 7, 5], [83, 5]),
  new Recipe('50', 'Pad Thai vegetariano', RECIPE_TYPES[4],
    'Spaghetti di riso saltati con uova, verdure e arachidi',
    6.0, null,
    [2, 6, 7, 5, 1], [83, 5]),
  new Recipe('50VEG', 'Pad Thai vegan', RECIPE_TYPES[4],
    'Spaghetti di riso saltati con verdure e arachidi',
    5.5, null,
    [2, 7, 5, 0], [5], [], [],
    '50'),
  new Recipe('51', 'Spaghetti di soia ai frutti di mare', RECIPE_TYPES[4],
    'Spaghetti di soia saltati con verdure e frutti di mare',
    5.0, null,
    [2, 4, 11, 12, 13, 1]),
  new Recipe('52', 'Spaghetti di soia con pollo', RECIPE_TYPES[4],
    'Spaghetti di soia saltati con verdure e pollo',
    4.5, null,
    [2, 4]),
  new Recipe('53', 'Spaghetti di soia vegan', RECIPE_TYPES[4],
    'Spaghetti di soia saltati con verdure',
    4.0, null,
    [2, 4, 0]),
  new Recipe('54', 'Fettuccine ai frutti di mare', RECIPE_TYPES[4],
    'Fettucine di frumento saltate con uova, verdure e frutti di mare',
    5.5, null,
    [2, 3, 11, 6, 12, 13, 15, 1], [83]),
  new Recipe('55', 'Fettuccine con pollo', RECIPE_TYPES[4],
    'Fettucine di frumento saltate con uova, verdure e pollo',
    5.0, null,
    [2, 3, 6], [83]),
  new Recipe('56', 'Fettuccine vegetariane', RECIPE_TYPES[4],
    'Fettucine di frumento saltate con uova e verdure',
    4.5, null,
    [2, 3, 6, 1], [83]),
  new Recipe('56VEG', 'Fettuccine vegan', RECIPE_TYPES[4],
    'Fettucine di frumento saltate con verdure',
    4.0, null,
    [2, 3, 0], [], [], [],
    '56'),
  new Recipe('57', 'Spaghetti di riso ai frutti di mare', RECIPE_TYPES[4],
    'Spaghetti di riso saltati con uova, verdure e frutti di mare',
    5.5, null,
    [2, 11, 6, 12, 13, 1], [83]),
  new Recipe('58', 'Spaghetti di riso con pollo', RECIPE_TYPES[4],
    'Spaghetti di riso saltati con uova, verdure e pollo',
    5.0, null,
    [2, 6], [83]),
  new Recipe('59', 'Spaghetti di riso vegetariano', RECIPE_TYPES[4],
    'Spaghetti di riso saltati con uova e verdure',
    4.5, null,
    [2, 6], [83]),
  new Recipe('59VEG', 'Spaghetti di riso vegan', RECIPE_TYPES[4],
    'Spaghetti di riso saltati con verdure',
    4.5, null,
    [2], [], [], [],
    '59'),
  new Recipe('60', 'Yaki tori', RECIPE_TYPES[5],
    'Spiedini di pollo',
    4.0, 2,
    [3, 4], [71]),
  new Recipe('61', 'Ebishino', RECIPE_TYPES[5],
    'Spiedini di gamberi',
    5.0, 2,
    [3, 4, 11, 13, 15, 1], [71]),
  new Recipe('62', 'Yaki ika', RECIPE_TYPES[5],
    'Spiedini di calamari',
    5.0, 2,
    [3, 4, 13, 15, 1], [71]),
  new Recipe('63', 'Gyuniku', RECIPE_TYPES[5],
    'Spiedini di manzo',
    7.0, 2,
    [3, 4], [71]),
  new Recipe('64', 'Yaki zakana', RECIPE_TYPES[5],
    'Spiedini di pesce misto',
    6.0, 2,
    [3, 4, 11, 12, 13, 15, 14, 1], [71]),
  new Recipe('65', 'Sake teriyaki', RECIPE_TYPES[5],
    'Spiedini di salmone',
    7.0, null,
    [3, 4, 13, 14, 1], [71]),
  new Recipe('66', 'Maguro teriyaki', RECIPE_TYPES[5],
    'Spiedini di tonno',
    8.0, null,
    [3, 4, 13, 14, 1], [71]),
  new Recipe('67', 'Ebi teriyaki', RECIPE_TYPES[5],
    'Spiedini di gamberone',
    6.0, 2,
    [3, 4, 11, 15, 1], [71]),
  new Recipe('68', 'Ebi tempura', RECIPE_TYPES[6],
    'Gamberi in tempura',
    6.0, 3,
    [3, 11, 6, 13, 15, 1]),
  new Recipe('69', 'Mandorle ebi tempura', RECIPE_TYPES[6],
    'Gamberi in crosta di mandorle',
    9.0, 3,
    [3, 11, 6, 7, 13, 15, 1]),
  new Recipe('70', 'Yasai tempura', RECIPE_TYPES[6],
    'Verdure stagionali in tempura',
    5.0, 4,
    [2, 3, 6, 1]),
  new Recipe('71', 'Tempura mix', RECIPE_TYPES[6],
    'Gamberi e Verdure stagionali in tempura',
    9.0, null,
    [2, 3, 6, 11, 13, 15, 1]),
  new Recipe('72', 'Ika tempura', RECIPE_TYPES[6],
    'Anello di calamari in panko',
    6.0, null,
    [3, 6, 13, 15, 1]),
  new Recipe('73', 'Tori karage', RECIPE_TYPES[6],
    'Bocconcini di pollo fritto',
    6.0, null,
    [3, 6]),
  new Recipe('74', 'Chicken furai', RECIPE_TYPES[6],
    'Cotoletta di pollo in panko',
    5.0, null,
    [3, 6]),
  new Recipe('75', 'Potato furai', RECIPE_TYPES[6],
    'Patatine fritte',
    3.0, null,
    [2, 15, 0], [53]),
  new Recipe('76', 'Salmon stick', RECIPE_TYPES[6],
    'Stick di salmone in panko',
    6.0, 3,
    [3, 6, 12, 15, 1], [53]),
  new Recipe('77', 'Pollo alle mandorle', RECIPE_TYPES[7],
    'Pollo alle mandorle',
    5.5, null,
    [2, 3, 4, 7]),
  new Recipe('78', 'Pollo al limone', RECIPE_TYPES[7],
    'Pollo al limone',
    5.5, null,
    [2]),
  new Recipe('79', 'Pollo all\'arancia', RECIPE_TYPES[7],
    'Pollo all\'arancia',
    5.5, null,
    [2]),
  new Recipe('80', 'Pollo piccante', RECIPE_TYPES[7],
    'Pollo piccante',
    5.5, null,
    [2, 5]),
  new Recipe('81', 'Pollo al curry', RECIPE_TYPES[7],
    'Pollo al curry',
    5.5, null,
    [2, 3]),
  new Recipe('82', 'Pollo agli anacardi', RECIPE_TYPES[7],
    'Pollo agli anacardi',
    5.5, null,
    [2, 3, 7]),
  new Recipe('83', 'Pollo bambù e funghi', RECIPE_TYPES[7],
    'Pollo bambù e funghi',
    5.5, null,
    [2, 4]),
  new Recipe('84', 'Pollo con verdure miste', RECIPE_TYPES[7],
    'Pollo con verdure miste',
    5.5, null,
    [2]),
  new Recipe('85', 'Pollo in agrodolce', RECIPE_TYPES[7],
    'Pollo in salsa agrodolce',
    5.0, null,
    [2]),
  new Recipe('86', 'Manzo bambù e funghi', RECIPE_TYPES[7],
    'Manzo bambù e funghi',
    6.5, null,
    [2, 3, 4]),
  new Recipe('87', 'Manzo al curry', RECIPE_TYPES[7],
    'Manzo al curry',
    7.0, null,
    [2, 3, 4]),
  new Recipe('88', 'Manzo in salsa d\'ostriche', RECIPE_TYPES[7],
    'Manzo in salsa d\'ostriche',
    7.0, null,
    [2, 3, 4, 13]),
  new Recipe('89', 'Manzo patate e verdure', RECIPE_TYPES[7],
    'Manzo con patate e verdure',
    7.0, null,
    [2, 3, 4]),
  new Recipe('90', 'Maiale in agrodolce', RECIPE_TYPES[7],
    'Maiale in salsa agrodolce',
    6.0, null,
    [2, 10]),
  /**/
  new Recipe('92', 'Gamberi sale e pepe', RECIPE_TYPES[8],
    'Gamberi sale e pepe',
    7.5, null,
    [2, 11, 15], [53]),
  new Recipe('93', 'Gamberi al curry', RECIPE_TYPES[8],
    'Gamberi al curry',
    7.5, null,
    [2, 11, 15]),
  new Recipe('94', 'Gamberi piccanti', RECIPE_TYPES[8],
    'Gamberi piccanti',
    7.5, null,
    [2, 11, 5, 15]),
  new Recipe('95', 'Gamberi al limone', RECIPE_TYPES[8],
    'Gamberi al limone',
    8.0, null,
    [2, 11, 15]),
  new Recipe('96', 'Gamberi all\'arancia', RECIPE_TYPES[8],
    'Gamberi all\'arancia',
    8.0, null,
    [2, 11, 15]),
  new Recipe('97', 'Gamberi in agrodolce', RECIPE_TYPES[8],
    'Gamberi in salsa agrodolce',
    7.5, null,
    [2, 11, 15]),
  new Recipe('98', 'Gamberi fritti', RECIPE_TYPES[8],
    'Gamberi fritti',
    8.0, null,
    [3, 6, 11, 15]),
  new Recipe('99', 'Gamberi bambù e funghi', RECIPE_TYPES[8],
    'Gamberi con bambù e funghi',
    7.5, null,
    [2, 3, 11, 15]),
  new Recipe('91', 'Calamari piccanti', RECIPE_TYPES[8],
    'Calamari piccanti',
    6.0, null,
    [2, 13, 5, 15]),
  new Recipe('100', 'Germogli di soia al wok', RECIPE_TYPES[9],
    'Germogli di soia al wok',
    5.5, null,
    [2, 0]),
  new Recipe('101', 'Verdure di stagione al wok', RECIPE_TYPES[9],
    'Verdure di stagione al wok',
    5.5, null,
    [2, 0]),
  new Recipe('110', 'Poke sake', RECIPE_TYPES[10],
    'Riso con salmone, avocado, edamame, cipolle fritte e sesamo',
    12.0, null,
    [2, 3, 12, 14, 1], [8, 19, 15, 72]),
  new Recipe('111', 'Poke ebiten', RECIPE_TYPES[10],
    'Riso con tempura di gamberi, avocado, edamame e wakame',
    11.0, null,
    [2, 3, 4, 6, 11, 15, 1], [8, 19, 89]),
  new Recipe('112', 'Poke special ZUMI', RECIPE_TYPES[10],
    'Riso con salmone, tonno, edamame, mandorle, avocado, surimi e ikura',
    13.0, null,
    [2, 3, 4, 7, 11, 12, 13, 15, 14, 1], [19, 41, 8, 78, 34]),
  new Recipe('113', 'Poke vegan', RECIPE_TYPES[10],
    'Riso con avocado, mango, wakame, edamame e cetriolo',
    9.0, null,
    [2, 0], [8, 42, 89, 19, 13]),
  new Recipe('114', 'Tacos sake', RECIPE_TYPES[11],
    'Taco con salmone marinato, guacamole e cipolla fritta',
    6.0, 1,
    [2, 3, 4, 12, 14, 1], [31, 15]),
  new Recipe('115', 'Tacos ebiten', RECIPE_TYPES[11],
    'Taco con gambero in tempura, philadelphia e insalta',
    6.0, 1,
    [2, 3, 4, 6, 9, 11, 15, 1], [55, 71]),
  new Recipe('102', 'Hoso sake', RECIPE_TYPES[12],
    'Hosomaki al salmone',
    4.0, 6,
    [12, 15, 1]),
  new Recipe('103', 'Hoso tekka', RECIPE_TYPES[12],
    'Hosomaki al tonno',
    4.0, 6,
    [12, 15, 1]),
  new Recipe('104', 'Hoso ebi', RECIPE_TYPES[12],
    'Hosomaki al gambero cotto',
    3.5, 6,
    [11, 15, 1]),
  new Recipe('105', 'Hoso sake flower', RECIPE_TYPES[12],
    'Hosomaki al salmone cotto e philadelphia',
    4.0, 6,
    [3, 4, 9, 12, 15, 1]),
  new Recipe('106', 'Hoso kani', RECIPE_TYPES[12],
    'Hosomaki al granchio',
    3.5, 6,
    [3, 11, 13, 15, 1]),
  new Recipe('107', 'Hoso mango', RECIPE_TYPES[12],
    'Hosomaki al mango',
    3.5, 6,
    [2, 0]),
  new Recipe('108', 'Hoso avocado', RECIPE_TYPES[12],
    'Hosomaki all\'avocado',
    3.5, 6,
    [2, 0]),
  new Recipe('109', 'Hoso kappa', RECIPE_TYPES[12],
    'Hosomaki al cetriolo',
    3.0, 6,
    [2, 0]),
  new Recipe('116', 'Sake avocado roll', RECIPE_TYPES[13],
    'Hosomaki al salmone con avocado ricoperto di sesamo',
    4.5, 4,
    [2, 12, 14, 1], [72]),
  new Recipe('117', 'Maguro avocado roll', RECIPE_TYPES[13],
    'Hosomaki al tonno con avocado ricoperto di sesamo',
    4.5, 4,
    [2, 12, 14, 1], [72]),
  new Recipe('118', 'Spice sake roll', RECIPE_TYPES[13],
    'Hosomaki al salmone piccante',
    4.5, 4,
    [3, 6, 5, 12, 14, 1]),
  new Recipe('119', 'Spice tuna roll', RECIPE_TYPES[13],
    'Hosomaki al tonno piccante',
    4.5, 4,
    [3, 6, 5, 12, 14, 1]),
  new Recipe('120', 'Philadelphia roll', RECIPE_TYPES[13],
    'Hosomaki al salmone con philadelphia e avocado ricoperto di tobiko',
    4.5, 4,
    [2, 9, 12, 13, 14, 15, 1], [79]),
  new Recipe('121', 'Rainbow roll', RECIPE_TYPES[13],
    'Hosomaki al salmone con avocado ricoperto di pesce misto',
    6.0, 4,
    [2, 12, 14, 1]),
  new Recipe('122', 'Mexican roll', RECIPE_TYPES[13],
    'Hosomaki al salmone con philadelphia, guacamole e nachos',
    6.5, 4,
    [2, 3, 9, 12, 14, 1]),
  new Recipe('123', 'Wasabi roll', RECIPE_TYPES[13],
    'Hosomaki di spigola con avocado e maionese al wasabi',
    6.0, 4,
    [2, 6, 5, 12, 14, 1], [39]),
  new Recipe('124', 'Tris roll', RECIPE_TYPES[13],
    'Hosomaki con salmone, tonno e spigola ricoperto di cipolla fritta',
    6.5, 4,
    [3, 12, 14, 1], [15]),
  new Recipe('125', 'Lime roll', RECIPE_TYPES[13],
    'Hosomaki al salmone piccante ricoperto di lime con salsa al tabasco',
    6.0, 4,
    [2, 6, 5, 12, 14, 1], [68]),
  new Recipe('126', 'Wakame roll', RECIPE_TYPES[13],
    'Hosomaki al salmone con avocado, ricoperto di wakame e salsa al sesamo',
    6.0, 4,
    [2, 12, 14, 15, 1], [67]),
  new Recipe('127', 'Ginger roll', RECIPE_TYPES[13],
    'Hosomaki al surimi in tempura ricoperto di zenzero marinato',
    5.5, 4,
    [2, 3, 6, 11, 13, 15, 1]),
  new Recipe('128', 'Pistacchio tuna roll', RECIPE_TYPES[13],
    'Hosomaki al tonno con avocado ricoperto di granella di pistacchio e maionese',
    6.5, 4,
    [2, 6, 7, 12, 14, 1], [39]),
  new Recipe('129', 'Tropical roll', RECIPE_TYPES[13],
    'Hosomaki al salmone con avocado ricoperto di mango e passion fruit',
    6.5, 4,
    [2, 12, 14, 1]),
  new Recipe('129VEG', 'Tropical vegan roll', RECIPE_TYPES[13],
    'Hosomaki con avocado ricoperto di mango e passion fruit',
    6.0, 4,
    [2, 0], [], [], [],
    '129'),
  new Recipe('130', 'Green tuna roll', RECIPE_TYPES[13],
    'Hosomaki al tonno con philadelphia e mela verde',
    6.5, 4,
    [2, 9, 12, 14, 1]),
  new Recipe('131', 'Fragola roll', RECIPE_TYPES[13],
    'Hosomaki al salmone con philadelphia e fragole',
    6.0, 4,
    [2, 3, 4, 9, 12, 14, 1], [71]),
  new Recipe('132', 'Mango roll', RECIPE_TYPES[13],
    'Hosomaki al salmone con philadelphia e mango',
    6.0, 4,
    [2, 3, 4, 9, 12, 14, 1], [71]),
  new Recipe('133', 'Felice roll', RECIPE_TYPES[13],
    'Hosomaki al salmone fritto e philadelphia ricoperto di salmone',
    5.5, 4,
    [3, 4, 9, 6, 12, 14, 1], [71]),
  new Recipe('134', 'Tartar roll', RECIPE_TYPES[13],
    'Hosomaki alle verdure fritte ricoperto di tartar al salmone',
    5.0, 4,
    [2, 3, 6, 5, 12, 14, 1], [68, 65]),
  new Recipe('135', 'Shibuya roll', RECIPE_TYPES[13],
    'Hosomaki al gambero fritto con philadelphia ricoperto di salmone e avocado',
    6.0, 4,
    [2, 3, 4, 6, 9, 11, 12, 14, 15, 1], [68]),
  new Recipe('136', 'Miura roll', RECIPE_TYPES[13],
    'Hosomaki al salmone cotto con philadelphia e avocado ricoperto di kataifi',
    4.5, 4,
    [2, 3, 4, 9, 12, 14, 1], [71]),
  new Recipe('137', 'California roll', RECIPE_TYPES[13],
    'Hosomaki al surimi con cetriolo e avocado',
    4.5, 4,
    [2, 3, 11, 13, 15, 1]),
  new Recipe('138', 'California special', RECIPE_TYPES[13],
    'Hosomaki al tonno in scatola, maionese, surimi e avocado',
    4.5, 4,
    [2, 3, 6, 11, 12, 13, 15, 1], [39]),
  new Recipe('139', 'Ebiten roll', RECIPE_TYPES[13],
    'Hosomaki al gambero fritto ricoperto di kataifi',
    5.0, 4,
    [3, 4, 6, 11, 15, 1], [71]),
  new Recipe('140', 'Tiger roll', RECIPE_TYPES[13],
    'Hosomaki al gambero fritto ricoperto di salmone flambè',
    5.5, 4,
    [3, 4, 6, 11, 15, 1], [71]),
  new Recipe('141', 'Dragon roll', RECIPE_TYPES[13],
    'Hosomaki al gambero fritto ricoperto di avocado',
    5.5, 4,
    [2, 3, 4, 6, 9, 11, 15, 1], [71]),
  new Recipe('142', 'Rucola roll', RECIPE_TYPES[13],
    'Hosomaki al gambero fritto ricoperto di salone flambè e rucola',
    5.5, 4,
    [2, 3, 4, 6, 11, 12, 14, 15, 1], [71]),
  new Recipe('143', 'Unaghi roll', RECIPE_TYPES[13],
    'Hosomaki con anguilla e philadelphia ricoperto di avocado',
    6.0, 4,
    [2, 3, 4, 9, 13, 15, 1], [71, 55]),
  new Recipe('144', 'Mandorle roll', RECIPE_TYPES[13],
    'Hosomaki con pollo fritto ricoperto di mandorle',
    5.0, 4,
    [3, 4, 6, 7], [71, 41]),
  new Recipe('145', 'Vegan roll', RECIPE_TYPES[13],
    'Hosomaki con cetriolo, avocado e mango',
    4.0, 4,
    [2, 0], [71, 41]),
  new Recipe('146', 'Maki fritto', RECIPE_TYPES[13],
    'Hosomaki con salmone, philadelphia e frutta di stagione',
    6.5, 6,
    [2, 3, 4, 6, 9, 12, 1], [71, 55]),
  new Recipe('147', 'Futomaki fritto', RECIPE_TYPES[13],
    'Hosomaki con salmone, tonno, surimi, cetriolo e avocado',
    7.0, 6,
    [2, 3, 4, 6, 11, 12, 13, 14, 15, 1], [71]),
  new Recipe('V1', 'Black venere philadelphia', RECIPE_TYPES[13],
    'Hosomaki al salmone con philadelphia e avocado ricoperto di tobiko',
    6.0, 4,
    [2, 9, 12, 13, 14, 15, 1], [55, 8]),
  new Recipe('V2', 'Black venere miura', RECIPE_TYPES[13],
    'Hosomaki al salmone cotto con philadelphia e avocado ricoperto di kataifi',
    5.5, 4,
    [2, 3, 4, 9, 12, 13, 14, 15, 1], [55, 8, 71]),
  new Recipe('V3', 'Black venere ebiten', RECIPE_TYPES[13],
    'Hosomaki al gambero fritto e kataifi',
    6.0, 4,
    [3, 4, 6, 11, 15, 1], [71]),
  new Recipe('V4', 'Black venere sake e avocado', RECIPE_TYPES[13],
    'Hosomaki al salmone con avocado e sesamo',
    5.5, 4,
    [2, 12, 14, 1], [8, 72]),
  new Recipe('V5', 'Black venere maguro e avocado', RECIPE_TYPES[13],
    'Hosomaki al tonno con avocado e sesamo',
    5.5, 4,
    [2, 12, 14, 1], [8, 72]),
  new Recipe('148', 'Nigiri sake', RECIPE_TYPES[14],
    'Nigiri al salmone',
    2.5, 2,
    [12, 14, 1]),
  new Recipe('149', 'Nigiri maguro', RECIPE_TYPES[14],
    'Nigiri al tonno',
    2.5, 2,
    [12, 14, 1]),
  new Recipe('150', 'Nigiri amaebi', RECIPE_TYPES[14],
    'Nigiri al gambero crudo',
    3.0, 2,
    [11, 13, 15, 1]),
  new Recipe('151', 'Nigiri ebi', RECIPE_TYPES[14],
    'Nigiri al gambero cotto',
    2.5, 2,
    [11, 15, 1]),
  new Recipe('152', 'Nigiri tako', RECIPE_TYPES[14],
    'Nigiri al polpo cotto',
    2.5, 2,
    [13, 15, 1]),
  new Recipe('153', 'Nigiri unaghi', RECIPE_TYPES[14],
    'Nigiri all\'anguilla',
    2.5, 2,
    [3, 4, 13, 15, 1], [71]),
  new Recipe('154', 'Nigiri mango', RECIPE_TYPES[14],
    'Nigiri al mango',
    2.5, 2,
    [0]),
  new Recipe('155', 'Nigiri avocado', RECIPE_TYPES[14],
    'Nigiri all\'avocado',
    2.5, 2,
    [0]),
  new Recipe('156', 'Nigiri sake flower', RECIPE_TYPES[14],
    'Nigiri al salmone scottato e philadelphia',
    3.5, 2,
    [3, 4, 9, 12, 14, 1], [55, 71]),
  new Recipe('157', 'Onigiri sake', RECIPE_TYPES[15],
    'Onigiri al salmone',
    3.0, 1,
    [12, 14, 1]),
  new Recipe('158', 'Onigiri special maguro', RECIPE_TYPES[15],
    'Onigiri al tonno in scatola e maionese',
    3.0, 1,
    [6, 12, 1], [83, 39]),
  new Recipe('159', 'Onigiri ebi', RECIPE_TYPES[15],
    'Onigiri al gambero cotto',
    3.0, 1,
    [11, 15, 1], [83, 39]),
  new Recipe('160', 'Sake temaki', RECIPE_TYPES[16],
    'Temaki al salmone con avocado',
    3.5, 1,
    [2, 12, 14, 1], [8]),
  new Recipe('161', 'Maguro temaki', RECIPE_TYPES[16],
    'Temaki al tonno con avocado',
    3.5, 1,
    [2, 12, 14, 1], [8]),
  new Recipe('162', 'Ebiten temaki', RECIPE_TYPES[16],
    'Temaki al gambero fritto con avocado',
    3.5, 1,
    [2, 3, 4, 6, 11, 15, 1], [8, 71]),
  new Recipe('163', 'Ebiten temaki', RECIPE_TYPES[16],
    'Temaki al gambero cotto con avocado',
    3.5, 1,
    [2, 11, 15, 1], [8]),
  new Recipe('164', 'Spicy sake temaki', RECIPE_TYPES[16],
    'Temaki al salmone piccante con avocado',
    3.5, 1,
    [2, 5, 6, 12, 14, 1], [8]),
  new Recipe('165', 'Spicy maguro temaki', RECIPE_TYPES[16],
    'Temaki al tonno piccante con avocado',
    3.5, 1,
    [2, 5, 6, 12, 14, 1], [8]),
  new Recipe('166', 'Philadelphia temaki', RECIPE_TYPES[16],
    'Temaki al salmone e philadelphia con avocado',
    4.0, 1,
    [2, 6, 12, 14, 1], [8]),
  new Recipe('167', 'Vegan temaki', RECIPE_TYPES[16],
    'Temaki al cetriolo, avocado e mango',
    3.5, 1,
    [2, 0]),
  new Recipe('168', 'Chirashi sake', RECIPE_TYPES[17],
    'Cupola di riso ricoperta di salmone',
    7.0, 1,
    [12, 14, 1]),
  new Recipe('169', 'Chirashi mix', RECIPE_TYPES[17],
    'Cupola di riso ricoperta di salmone e tonno',
    7.5, 1,
    [12, 14, 1]),
  new Recipe('170', 'Sashimi sake', RECIPE_TYPES[18],
    'Sashimi di salmone',
    5.0, 5,
    [12, 14, 1]),
  new Recipe('171', 'Sashimi tai', RECIPE_TYPES[18],
    'Sashimi di spigola',
    5.0, 5,
    [12, 14, 1]),
  new Recipe('172', 'Sashimi maguro', RECIPE_TYPES[18],
    'Sashimi di tonno',
    6.0, 5,
    [12, 14, 1]),
  new Recipe('173', 'Sashimi mix', RECIPE_TYPES[18],
    'Sashimi misto',
    12.0, 13,
    [12, 14, 1]),
  new Recipe('174', 'Tartare sake', RECIPE_TYPES[8],
    'Tartare di salmone marinato con mango e avocado',
    8.0, null,
    [2, 3, 4, 12, 14, 1]),
  new Recipe('175', 'Tartare maguro', RECIPE_TYPES[8],
    'Tartare di tonno marinato con mango e avocado',
    8.5, null,
    [2, 3, 4, 12, 14, 1]),
  new Recipe('176', 'Tartare sake venerde', RECIPE_TYPES[8],
    'Tartare di salmone marinato su letto di riso venere',
    10.0, null,
    [2, 12, 14, 1]),
  new Recipe('177', 'Carpaccio di salmone', RECIPE_TYPES[8],
    'Carpaccio di salmone marinato in salsa di agrumi',
    8.0, 10,
    [3, 4, 12, 14, 1]),
  new Recipe('178', 'Carpaccio mix', RECIPE_TYPES[8],
    'Carpaccio di pesce misto marinato in salsa di agrumi',
    10.0, 12,
    [3, 4, 12, 14, 1]),
  new Recipe('179', 'Carpaccio Zumi', RECIPE_TYPES[8],
    'Carpaccio di salmone e gamberetti marinati in salsa ponzu con cipollina e olio',
    11.0, 10,
    [2, 3, 4, 11, 12, 14, 15, 1]),
  new Recipe('180', 'Philadelphia gunkan', RECIPE_TYPES[19],
    'Gunkan al salmone e philadelphia',
    3.5, 2,
    [9, 12, 14, 1]),
  new Recipe('181', 'Sake gunkan', RECIPE_TYPES[19],
    'Gunkan al salmone con tartare di salmone',
    3.5, 2,
    [6, 5, 12, 14, 1], [68]),
  new Recipe('182', 'Guacamole gunkan', RECIPE_TYPES[19],
    'Gunkan al salmone con guacamole',
    3.5, 2,
    [2, 12, 14, 1]),
  new Recipe('183', 'Ikura gunkan', RECIPE_TYPES[19],
    'Gunkan con uova di salmone',
    4.0, 2,
    [13, 15, 1]),
  new Recipe('184', 'Tobiko gunkan', RECIPE_TYPES[19],
    'Gunkan con uova di pesce volante',
    3.5, 2,
    [13, 15, 1]),
  new Recipe('185', 'Maguro gunkan', RECIPE_TYPES[19],
    'Gunkan al tonno con tartare di tonno',
    3.5, 2,
    [6, 5, 12, 14, 1]),
  new Recipe('186', 'Wakame gunkan', RECIPE_TYPES[19],
    'Gunkan con wakame',
    3.5, 2,
    [2, 15, 1]),
  new Recipe('187', 'Nigiri misto', RECIPE_TYPES[20],
    'Nigiri assortiti',
    7.0, 6),
  new Recipe('188', 'Sushi mix small', RECIPE_TYPES[20],
    '4 nigiri, 2 uramaki e 2 hosomaki assortiti',
    8.0, 8),
  new Recipe('189', 'Sushi mix single', RECIPE_TYPES[20],
    '16 pezzi assortiti fra nigiri, uramaki, hosomaki e sashimi',
    16.0, 16),
  new Recipe('190', 'Sushi mix double', RECIPE_TYPES[20],
    '32 pezzi misti fra nigiri, uramaki, hosomaki e sashimi, serviti al tavolo in una barca',
    32.0, 32),
  new Recipe('191', 'Sushi mix family', RECIPE_TYPES[20],
    '54 pezzi misti fra nigiri, uramaki, hosomaki e sashimi, serviti al tavolo in una barca',
    54.0, 54),
  new Recipe('D1', 'Dorayaki', RECIPE_TYPES[21],
    'Il famoso dolce di Doraemon, pancake Giapponesi ripieno di nutella',
    6.0, null,
    [], [50]),
  new Recipe('D2', 'Mochi', RECIPE_TYPES[21],
    'Dolce di riso ripieno al gelato',
    5.0),
  new Recipe('D3', 'Tiramisù verde', RECIPE_TYPES[21],
    'Variante Giapponese del Tiramisù nostrano',
    6.0),
  new Recipe('D4', 'Tiramisù alla nutella', RECIPE_TYPES[21],
    'Variante della casa del Tiramisù con aggiunta di Nutella',
    6.0),
  new Recipe('D5', 'Daifuku', RECIPE_TYPES[21],
    'Dolce di riso con ripieno ai fagioli rossi',
    5.0),
  new Recipe('D6', 'Soufflé al cioccolato', RECIPE_TYPES[21],
    'Soufflé al cioccolato',
    5.5, null,
    [], [50]),
  new Recipe('D7', 'Nutella maki', RECIPE_TYPES[21],
    'Maki ricreati con crepe ripiena al gelato con nutella, panna e scaglie di cocco',
    6.5, null,
    [], [50]),
  new Recipe('D8', 'Gelato giapponese bigusto', RECIPE_TYPES[21],
    'Tè verde, sesamo, zenzero e riso',
    4.0),
  new Recipe('D9', 'Sorbetto al limone', RECIPE_TYPES[21],
    'Sorbetto al limone',
    3.5),
  new Recipe('D10', 'Creme brulèe', RECIPE_TYPES[21],
    'Creme brulèe',
    5.0),
  new Recipe('D11', 'Cheesecake fredda', RECIPE_TYPES[21],
    'Gusto a scelta',
    6.0, null,
    [], [50]),
  new Recipe(null, 'Acqua', RECIPE_TYPES[22],
    '750 ml',
    2.0, null,
    [], [], [], [],
    'acqua750'),
  new Recipe(null, 'Acqua', RECIPE_TYPES[22],
    '500 ml',
    1.5, null,
    [], [], [], [],
    'acqua500',
    'Acqua 50cl'),
  new Recipe(null, 'Coca cola', RECIPE_TYPES[22],
    '330 ml',
    2.5, null,
    [], [], [], [],
    'coca330ml',
    'Coca cola 33cl'),
  new Recipe(null, 'Coca cola zero', RECIPE_TYPES[22],
    '330 ml',
    2.5, null,
    [], [], [], [],
    'cocazero330ml',
    'Coca zero 33cl'),
  new Recipe(null, 'Coca cola', RECIPE_TYPES[22],
    '1 l',
    4.0, null,
    [], [], [], [],
    'coca1l',
    'Coca cola 1l'),
  new Recipe(null, 'Fanta', RECIPE_TYPES[22],
    '330 ml',
    2.5, null,
    [], [], [], [],
    'fanta330ml'),
  new Recipe(null, 'Sprite', RECIPE_TYPES[22],
    '330 ml',
    2.5, null,
    [], [], [], [],
    'sprite330ml'),
  new Recipe(null, 'Tè al limone', RECIPE_TYPES[22],
    '330 ml',
    2.5, null,
    [], [], [], [],
    'tealemon330ml'),
  new Recipe(null, 'Tè alla pesca', RECIPE_TYPES[22],
    '330 ml',
    2.5, null,
    [], [], [], [],
    'teapeach330ml'),
  new Recipe(null, 'Tè verde caldo', RECIPE_TYPES[22],
    'Preparato da noi',
    3.5, null,
    [], [], [], [],
    'teagreen'),
  new Recipe(null, 'Tè al gelsomino caldo', RECIPE_TYPES[22],
    'Preparato da noi',
    3.5, null,
    [], [], [], [],
    'teajasmine'),
  new Recipe(null, 'Birra Asahi', RECIPE_TYPES[22],
    '330 ml',
    4.0, null,
    [], [], [], [],
    'asahi330ml',
    'Birra Asahi - 330ml'),
  new Recipe(null, 'Birra Asahi', RECIPE_TYPES[22],
    '500 ml',
    5.0, null,
    [], [], [], [],
    'asahi500ml',
    'Birra Asahi - 500ml'),
  new Recipe(null, 'Birra Sapporo', RECIPE_TYPES[22],
    '650 ml',
    6.0, null,
    [], [], [], [],
    'sapporo'),
  new Recipe(null, 'Birra Tsingtao', RECIPE_TYPES[22],
    '640 ml',
    5.5, null,
    [], [], [], [],
    'tsingtao'),
  new Recipe(null, 'Birra Heineken', RECIPE_TYPES[22],
    '660 ml',
    4.5, null,
    [], [], [], [],
    'heineken')
];

RECIPES.forEach((recipe: Recipe, index: number) => {
  recipe.id = index;
});
